# Generated by Django 4.2.8 on 2023-12-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio")),
                (
                    "uploaded_photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocr.uploadedphoto",
                    ),
                ),
            ],
        ),
    ]
