# Generated by Django 4.2.8 on 2023-12-15 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0002_audiofile"),
    ]

    operations = [
        migrations.RemoveField(model_name="audiofile", name="uploaded_photo",),
        migrations.AddField(
            model_name="audiofile",
            name="upload_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
